version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 757323807332.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t 757323807332.dkr.ecr.us-east-1.amazonaws.com/codebuild123:latest .
      - docker push 757323807332.dkr.ecr.us-east-1.amazonaws.com/codebuild123:latest
